general:
  seed: 0
  wandb_disabled: false
  freeze_encoder: true # Freeze encoder for finetuning
  resume_training: false
  log_dir: "./save_ckpt/run_interplane_recon"
  output_dir: "./save_ckpt/run_interplane_recon"
  ckpt_path: "" # Checkpoint to RESUME finetuning (not pretrain weights)
  pretrained_path: "./save_ckpt/run_pretrain/checkpoint-299.pth"
  save_ckpt_freq: 5
  device: "cuda"
  resume: ""
  auto_resume: false

data:
  processed_dir: "./train_data"
  num_train: 1000
  num_val: 10
  num_test: 10
  load_seg: true        # Enable loading segmentation masks
  augment: false        # Note: Datasets currently disable aug if load_seg=True
  image_size: 112
  time_frame: 32 # Restored
  decoder_feature: 32  # UNETR: feature_size=32. Switch to 128 if using seg_lite (VolSegDecoder)
  sax_slice_num: 6
  tubelet_size: 8
  img_patch_size: [4,4]
  mask_ratio: 0.0       # Disable masking for segmentation
  batch_size: 4
  num_workers: 8
  dataset_cls: "Cardiac3DplusTAllAX"
  pin_mem: true
  num_classes: 6

module:
  module_name: "pretrain_multivideomae_tiny_patch4_112" # pretrain_multivideomae_tiny_patch4_112
  #pretrain_multivideomae_tiny_patch4_112
  
  optimizer_params:
    lr: 1e-4
    min_lr: 1e-6
    warmup_lr: 1e-5
    use_checkpoint: false
    opt: "adamw"
    weight_decay: 0.05
    weight_decay_end: null
    opt_eps: 1e-8
    opt_betas: null
    drop_path: 0.1
    start_epoch: 0
    clip_grad: null
    momentum: 0.9

  secheduler_params:
    epochs: 50
    warmup_steps: -1
    warmup_epochs: 5
